import{S as u,N as p,K as m,A as h,a as f,i as c}from"./assets/vendor-cRKnTd4S.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const y={body:document.body,reviewsList:document.querySelector(".reviews-list")};new u(".swiper",{modules:[p,m],direction:"horizontal",loop:!0,hashNavigation:!0,keyboard:{enabled:!0,onlyInViewport:!1},ousewheel:{forceToAxis:!0},watchOverflow:!1,breakpoints:{320:{slidesPerView:2},768:{slidesPerView:3},1440:{slidesPerView:6}},navigation:{nextEl:".about-btn-next"}});new h(".accordion-container");document.addEventListener("DOMContentLoaded",()=>{new u(".project-swiper-wrapper",{modules:[p,m],slidesPerView:1,loop:!1,direction:"horizontal",navigation:{nextEl:".swiper-project-right",prevEl:".swiper-project-left"},keyboard:{enabled:!0},on:{slideChange:function(){r(this)}}});function r(s){const i=document.querySelector(".swiper-project-left"),n=document.querySelector(".swiper-project-right");s.isBeginning?i.setAttribute("disabled",!0):i.removeAttribute("disabled"),s.isEnd?n.setAttribute("disabled",!0):n.removeAttribute("disabled")}});document.addEventListener("DOMContentLoaded",function(){const r=document.querySelectorAll(".marquee"),s=new IntersectionObserver((i,n)=>{i.forEach(e=>{e.isIntersecting?(e.target.classList.add("active"),e.target.querySelectorAll(".marquee-line").forEach(l=>{l.style.animationPlayState="running"})):(e.target.classList.remove("active"),e.target.querySelectorAll(".marquee-line").forEach(l=>{l.style.animationPlayState="paused"}))})},{threshold:.1});r.forEach(i=>{s.observe(i)})});new u(".swiper",{modules:[p,m],direction:"horizontal",watchOverflow:!1,speed:700,spaceBetween:16,breakpoints:{320:{slidesPerView:1},768:{slidesPerView:2},1440:{slidesPerView:4}},keyboard:{enabled:!0},navigation:{nextEl:".reviews-btn-next",prevEl:".reviews-btn-prev"}});f.defaults.baseURL="https://portfolio-js.b.goit.study/api/reviews";async function w(){try{return(await f.get()).data}catch(r){throw console.log(r),r}}function b(r){return r.map(({_id:s,author:i,avatar_url:n,review:e})=>`
        <li class="swiper-slide reviews-list-item">
          <img
            class="reviews-item-img"
            src="${n}"
            alt="${i}"
            width="48"
            height="48"
            loading="lazy"
          />
          <h3 class="reviews-item-title section-subtitle">${i}</h3>
          <p class="reviews-item-text section-text">
           ${e}
          </p>
        </li>`).join("")}async function S(){try{const r=await w();y.reviewsList.insertAdjacentHTML("beforeend",b(r))}catch(r){console.log(r),c.error({message:"Sorry, the server is not responding!",position:"topRight",backgroundColor:"#ef4040",messageColor:"white",messageSize:"16",theme:"dark"}),y.reviewsList.insertAdjacentHTML("beforeend",'<li class="item-message"><p>Not Found</p></li>')}}S();const d=document.querySelector(".work-tgt-form"),v=document.querySelector("[data-modal]"),L=document.querySelector("[data-modal-close]"),q=document.querySelector("[data-send]"),o=d.querySelector('input[type="email"]'),a=o.nextElementSibling;function g(){o.value.length>0?o.validity.valid?(o.classList.add("valid"),o.classList.remove("invalid"),a.querySelector(".valid-feedback").style.display="block",a.querySelector(".invalid-feedback").style.display="none"):(o.classList.add("invalid"),o.classList.remove("valid"),a.querySelector(".valid-feedback").style.display="none",a.querySelector(".invalid-feedback").style.display="block"):(o.classList.remove("valid","invalid"),a.querySelector(".valid-feedback").style.display="none",a.querySelector(".invalid-feedback").style.display="none")}o.addEventListener("blur",function(){g()});q.addEventListener("click",async r=>{var e;if(r.preventDefault(),g(),!o.validity.valid){c.error({title:"Error",message:"Please enter a valid email address.",position:"topRight"});return}const s=new FormData(d),i=s.get("comment");if(!i.trim()){c.error({title:"Error",message:"Comment field cannot be empty.",position:"topRight"});return}const n={email:s.get("email"),comment:i};try{const t=await f.post("https://portfolio-js.b.goit.study/api/requests",JSON.stringify(n),{headers:{"Content-Type":"application/json"}});t.status>=200&&t.status<300&&(v.classList.remove("is-hidden"),d.reset(),o.classList.remove("valid","invalid"),a.querySelector(".valid-feedback").style.display="none",a.querySelector(".invalid-feedback").style.display="none")}catch(t){throw console.error("Error fetching images:",t),console.error("Error details:",(e=t.response)==null?void 0:e.data),c.error({title:"Error",message:"Something went wrong. Please check your input and try again.",position:"topRight"}),t}});L.addEventListener("click",()=>{v.classList.add("is-hidden")});
//# sourceMappingURL=commonHelpers.js.map
